In [1]:
import pandas as pd
import datetime

In [2]:
etf = pd.read_excel('ETF_Vol_Alt_Group16.xlsx', 'Updated ETF list',usecols='A,C',header=0)
df = pd.DataFrame(etf)
df.set_index('Issuer', inplace=True)
print(df)

dates = {'Date': pd.date_range(start='2015-12-31', end='2019-03-15')}
data = pd.DataFrame(data=dates)
data['Date'] = pd.to_datetime(data['Date']) 


print (data)

                         Symbol
Issuer
IndexIQ                     QAI
IndexIQ                     MNA
WisdomTree                 WTMF
First Trust                FTLS
WisdomTree                 DYLS
State Street SPDR           RLY
Reality Shares             DIVY
IndexIQ                     CPI
Exchange Traded Concepts   HTUS
AGFiQ Asset Management     BTAL
ProShares                   HDG
Cambria                    VAMO
IndexIQ                     QMN
Exchange Traded Concepts   FLAG
First Trust                 FMF
ProShares                  RALS
AGFiQ Asset Management      MOM
ProShares                  ALTS
IndexIQ                    MCRO
IndexIQ                     QLS
ProShares                  MRGR
AGFiQ Asset Management     DIVA
IndexIQ                     QED
AGFiQ Asset Management      SIZ
AGFiQ Asset Management     CHEP
ProShares                  SVXY
Credit Suisse              TVIX
ProShares                  UVXY
ProShares                  VIXY
Credit Suisse               ZIV
ProShares                  VIXM
Credit Suisse              VIIX
Barclays Capital            XVZ
           Date
0    2015-12-31
1    2016-01-01
2    2016-01-02
3    2016-01-03
4    2016-01-04
5    2016-01-05
6    2016-01-06
7    2016-01-07
8    2016-01-08
9    2016-01-09
10   2016-01-10
11   2016-01-11
12   2016-01-12
13   2016-01-13
14   2016-01-14
15   2016-01-15
16   2016-01-16
17   2016-01-17
18   2016-01-18
19   2016-01-19
20   2016-01-20
21   2016-01-21
22   2016-01-22
23   2016-01-23
24   2016-01-24
25   2016-01-25
26   2016-01-26
27   2016-01-27
28   2016-01-28
29   2016-01-29
...         ...
1141 2019-02-14
1142 2019-02-15
1143 2019-02-16
1144 2019-02-17
1145 2019-02-18
1146 2019-02-19
1147 2019-02-20
1148 2019-02-21
1149 2019-02-22
1150 2019-02-23
1151 2019-02-24
1152 2019-02-25
1153 2019-02-26
1154 2019-02-27
1155 2019-02-28
1156 2019-03-01
1157 2019-03-02
1158 2019-03-03
1159 2019-03-04
1160 2019-03-05
1161 2019-03-06
1162 2019-03-07
1163 2019-03-08
1164 2019-03-09
1165 2019-03-10
1166 2019-03-11
1167 2019-03-12
1168 2019-03-13
1169 2019-03-14
1170 2019-03-15

[1171 rows x 1 columns]

In [3]:
ProShares=df.at['ProShares','Symbol']
print(ProShares)

['HDG' 'RALS' 'ALTS' 'MRGR' 'SVXY' 'UVXY' 'VIXY' 'VIXM']

In [4]:
for symbol in ProShares:
    etf= pd.read_csv(symbol+'.csv',usecols = ['Date', 'NAV'])
    df = pd.DataFrame(etf)
    df['Date'] = pd.to_datetime(df['Date']) 
    df = df.set_index('Date')
    df.rename(columns={'NAV': symbol}, inplace=True)
    df=(df.truncate(after = '2015-12-31'))
    print(df.head(5))
    data = pd.merge(data,df,on = 'Date')


data.to_excel('NAV.xlsx', sheet_name='NAV')
print(data.head(5))

              HDG
Date
2019-03-15  45.29
2019-03-14  45.15
2019-03-13  45.19
2019-03-12  45.10
2019-03-11  45.07
             RALS
Date
2019-03-15  35.50
2019-03-14  35.54
2019-03-13  35.54
2019-03-12  35.54
2019-03-11  35.54
             ALTS
Date
2019-03-15  37.20
2019-03-14  37.13
2019-03-13  37.18
2019-03-12  37.09
2019-03-11  37.13
             MRGR
Date
2019-03-15  37.25
2019-03-14  37.27
2019-03-13  37.27
2019-03-12  37.27
2019-03-11  37.24
                 SVXY
Date
2019-03-15  53.503184
2019-03-14  52.726881
2019-03-13  52.471381
2019-03-12  52.077378
2019-03-11  51.563403
                 UVXY
Date
2019-03-15  37.435470
2019-03-14  39.173765
2019-03-13  39.758597
2019-03-12  40.684799
2019-03-11  41.946139
                 VIXY
Date
2019-03-15  23.333612
2019-03-14  24.044583
2019-03-13  24.282086
2019-03-12  24.655581
2019-03-11  25.159110
                 VIXM
Date
2019-03-15  21.059856
2019-03-14  21.296217
2019-03-13  21.256047
2019-03-12  21.462314
2019-03-11  21.611624
        Date    HDG   RALS   ALTS   MRGR      SVXY      UVXY     VIXY     VIXM
0 2015-12-31  42.02  38.78  38.16  36.26  101.6292  14042.45  264.868  53.9619
1 2016-01-04  41.77  38.98  38.06  36.21   96.3316  15506.05  278.668  55.0204
2 2016-01-05  41.78  38.91  38.09  36.26   97.8880  15002.75  274.138  54.2558
3 2016-01-06  41.57  38.81  38.01  36.37   94.3748  16076.85  283.952  55.1339
4 2016-01-07  41.24  38.81  37.70  36.27   83.0264  19939.90  318.068  57.9908